name: main

on:
  push:
    paths-ignore:
      - .github/**
    branches:
      - main

jobs:
#dev
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/niraljatinbhai.dave@infosys.com/DEV_MFG_GITHUB

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install notebook linting tools
        run: pip install nbqa black flake8

      - name: Format notebooks with Black
        run: nbqa black . --line-length 120

      - name: Lint notebooks with Flake8
        run: nbqa flake8 . --max-line-length=120 --ignore=E402,E501

      - name: Install dependencies
        run: |
          [ -f requirements.txt ] && pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run tests
        run: |
          [ -d tests ] && pip install pytest && pytest || echo "No tests directory found"

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (Dev)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}"

#prod
  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production
    env:
      DATABRICKS_HOST: ${{ secrets.PROD_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.PROD_DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/niraljatinbhai.dave@infosys.com/PROD_FIN_GITHUB

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch_prod
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (Prod)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch_prod.outputs.branch }}"